"use client"

export interface PredefinedReport {
  key: string
  name: string
  description: string
}

export const PREDEFINED_REPORTS: PredefinedReport[] = [
  {
    key: "overview",
    name: "Campaign Overview",
    description: "Overall performance across all campaigns",
  },
  {
    key: "leads_by_platform",
    name: "Leads by Platform",
    description: "Lead distribution across marketing platforms",
  },
  {
    key: "conversion_by_source",
    name: "Conversion by Source",
    description: "Conversion rates by traffic source",
  },
  {
    key: "deal_value_by_campaign",
    name: "Deal Value by Campaign",
    description: "Revenue generated by each campaign",
  },
  {
    key: "appointment_rate",
    name: "Appointment Rate",
    description: "Appointment booking rates by platform",
  },
]

interface MarketingPredefinedReportsSelectorProps {
  selectedReport: PredefinedReport
  onReportChange: (report: PredefinedReport) => void
}

export default function MarketingPredefinedReportsSelector({
  selectedReport,
  onReportChange,
}: MarketingPredefinedReportsSelectorProps) {
  return (
    <div className="bg-white rounded-lg shadow p-6">
      <h3 className="text-lg font-semibold text-gray-900 mb-4">Report Views</h3>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4">
        {PREDEFINED_REPORTS.map((report) => (
          <button
            key={report.key}
            onClick={() => onReportChange(report)}
            className={`p-4 rounded-lg border-2 text-left transition-all ${
              selectedReport.key === report.key
                ? "border-blue-500 bg-blue-50 text-blue-900"
                : "border-gray-200 hover:border-gray-300 hover:bg-gray-50"
            }`}
          >
            <h4 className="font-medium text-sm mb-1">{report.name}</h4>
            <p className="text-xs text-gray-600">{report.description}</p>
          </button>
        ))}
      </div>
    </div>
  )
}
